import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Text, Title } from '@mantine/core'
import Hero from '@/Components/Main/Hero'
import Link from 'next/link'
import Sluzby from '@/Components/Main/Sluzby'
import Features from '@/Components/Main/Features'
import Reference from '@/Components/Main/Reference'
import { FAQ } from '@/Components/Main/FAQ'
import useMobile from '@/Components/UI/useMobile'
import CTA from '@/Components/Main/CTA'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const mobile = useMobile()
  return (
    <>
      <Head>
        <title>Jirkova Tesla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
    <Hero />

        <div className={styles.grid}>
          <Link
            href="/nabidka"
            className={styles.card}
         
          >
            <h2>
              Nabídka <span>-&gt;</span>
            </h2>
            <p>
            Zjistěte více o našich flexibilních možnostech pronájmu a objevte, jak naše Tesla Model S může obohatit vaše zážitkové jízdy, firemní akce, cestování nebo společenské události.
            </p>
          </Link>

          <Link
            href="/onas"
            className={styles.card}
         
          >
            <h2>
              O nás <span>-&gt;</span>
            </h2>
            <p>
            Seznamte se s naším týmem a naší filosofií. Dozvíte se více o naší vášni pro elektromobilitu a našem závazku poskytovat prvotřídní zážitky z jízdy v Tesla Model S.
            </p>
          </Link>

          <Link
            href="/galerie"
            className={styles.card}
         
          >
            <h2>
            Galerie <span>-&gt;</span>
            </h2>
            <p>
            Prohlédněte si naše fotografie a videa z posledních zážitkových jízd, firemních akcí a dalších událostí s naší Tesla Model S.
            </p>
          </Link>

          <Link
            href="/rezervace"
            className={styles.card}
         
          >
            <h2>
            Rezervace <span>-&gt;</span>
            </h2>
            <p>
            Jednoduše a rychle si rezervujte vaši Tesla Model S online. Vyberte si termín, který vám nejlépe vyhovuje, a zažijte rychlost budoucnosti.
            </p>
          </Link>
          <Link
            href="/kontakt"
            className={styles.card}
         
          >
            <h2>
            Kontakt <span>-&gt;</span>
            </h2>
            <p>
            Máte nějaké otázky nebo potřebujete pomoc? Kontaktujte nás, jsme vám k dispozici. Naše tým je připraven vám poskytnout veškeré informace a podporu.
            </p>
          </Link>
        </div>
        <Sluzby mobile={mobile}/>
        <Features mobile={mobile}/>
        <Reference mobile={mobile}/>
        <FAQ mobile={mobile}/>
        <CTA mobile={mobile}/>
      </main>
    </>
  )
}
